
server:
  port:8080

spring:
    cloud:
      gateway:
        routes:
         - id: user service
           uri: https://kamalauserservice.onrender.com/user/register
           predicates:
            - Path=/user/**
           filters:
            - StripPrefix=1


         - id: book service
           uri: https://kamalabookservice.onrender.com/book/list
           predicates:
             - Path=/book/**
           filters:
             - StripPrefix=1

         - id: book management
           uri: https://kamalabookmanagement.onrender.com
           predicates:
             - Path=/catalog/**
           filters:
             - StripPrefix=1

